### ISSUE TITLE
开发这个包的源码可以分享一下吗？

### ISSUE THREAD

**Issue by fanite** [ycgambo/laravel-vue-templates#4]
我想将自己项目的一些功能模块做成一个个composer包，但是不知道怎么弄，我每次编译就要手动publish太麻烦了

**Comment by ycgambo** [comment]
https://packagist.org 了解一下

**Comment by ycgambo** [comment]
项目的源码主要是两部分，一部分是这个仓库，另一部分是vue模板，npm再打包出来js压缩包，这个仓库里面就是现成的压缩包。

关于composer包的生成，和项目无关，需要在上面的网站上配置，具体你去看一下文档就可以了。

**Comment by fanite** [comment]
谢谢你的回答，这个问题我了解了。
